#ifndef TOKENTYPE_H
#define TOKENTYPE_H

enum class TokenType {
	// single character
	LEFT_PARENTHESE, RIGHT_PARENTHESE, LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

	// comparisons
	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

	// literals
	IDENTIFIER, STRING, NUMBER,

	// keywords
	NIL, AND, OR, IF, ELSE, FOR, WHILE, TRUE, FALSE, PRINT, VAR, 
	FUN, RETURN, CLASS, SUPER, THIS,

	END_OF_FILE, EMPTY
};

#endif
